CREATE TABLE IF NOT EXISTS usuarios (
 id BIGSERIAL PRIMARY KEY,nombre_completo VARCHAR(150) NOT NULL,correo VARCHAR(190) NOT NULL UNIQUE,telefono VARCHAR(30),password VARCHAR(255) NOT NULL,tipo_usuario VARCHAR(20) NOT NULL DEFAULT 'cliente' CHECK(tipo_usuario IN ('cliente','productor','empresa')),rol VARCHAR(20) NOT NULL DEFAULT 'cliente' CHECK(rol IN ('cliente','administrador')),estado VARCHAR(20) NOT NULL DEFAULT 'activo' CHECK(estado IN ('activo','inactivo','bloqueado')),fecha_registro TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS disponibilidad_semanal (
 id BIGSERIAL PRIMARY KEY,semana_inicio DATE NOT NULL,semana_fin DATE NOT NULL,genero VARCHAR(10) NOT NULL CHECK(genero IN ('macho','hembra')),cajas_totales INTEGER NOT NULL DEFAULT 0 CHECK(cajas_totales>=0),cajas_reservadas INTEGER NOT NULL DEFAULT 0 CHECK(cajas_reservadas>=0),cajas_disponibles INTEGER NOT NULL DEFAULT 0 CHECK(cajas_disponibles>=0),estado VARCHAR(20) NOT NULL DEFAULT 'abierta' CHECK(estado IN ('abierta','cerrada','agotada')),fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(semana_inicio,semana_fin,genero),CHECK(semana_fin>=semana_inicio),CHECK(cajas_reservadas<=cajas_totales),CHECK(cajas_disponibles<=cajas_totales));
CREATE TABLE IF NOT EXISTS reservas (
 id BIGSERIAL PRIMARY KEY,codigo_reserva VARCHAR(30) NOT NULL UNIQUE,usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON UPDATE CASCADE ON DELETE RESTRICT,disponibilidad_id BIGINT NOT NULL REFERENCES disponibilidad_semanal(id) ON UPDATE CASCADE ON DELETE RESTRICT,semana_inicio DATE NOT NULL,semana_fin DATE NOT NULL,genero VARCHAR(10) NOT NULL CHECK(genero IN ('macho','hembra')),cantidad_cajas INTEGER NOT NULL CHECK(cantidad_cajas>=1),pollitos_por_caja INTEGER NOT NULL DEFAULT 100,pollitos_adicionales INTEGER NOT NULL DEFAULT 0,total_pollitos_aproximado INTEGER NOT NULL,estado VARCHAR(20) NOT NULL DEFAULT 'pendiente' CHECK(estado IN ('pendiente','confirmada','cancelada','completada','rechazada')),comentarios TEXT,fecha_reserva TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,fecha_confirmacion TIMESTAMPTZ,fecha_cancelacion TIMESTAMPTZ,fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS entregas (id BIGSERIAL PRIMARY KEY,reserva_id BIGINT NOT NULL UNIQUE REFERENCES reservas(id) ON DELETE RESTRICT,direccion VARCHAR(255) NOT NULL,detalles_entrega TEXT,latitud NUMERIC(10,7),longitud NUMERIC(10,7),persona_recibe VARCHAR(150) NOT NULL,telefono_recibe VARCHAR(30) NOT NULL,fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mensajes_contacto (id BIGSERIAL PRIMARY KEY,usuario_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,nombre VARCHAR(150) NOT NULL,correo VARCHAR(190) NOT NULL,asunto VARCHAR(200) NOT NULL,mensaje TEXT NOT NULL,estado VARCHAR(20) NOT NULL DEFAULT 'nuevo' CHECK(estado IN ('nuevo','leido','atendido','archivado')),fecha_envio TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,fecha_atencion TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS notificaciones (id BIGSERIAL PRIMARY KEY,usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,reserva_id BIGINT REFERENCES reservas(id) ON DELETE SET NULL,titulo VARCHAR(150) NOT NULL,contenido TEXT NOT NULL,leida BOOLEAN NOT NULL DEFAULT FALSE,fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS informacion_institucional (id BIGSERIAL PRIMARY KEY,clave VARCHAR(80) NOT NULL UNIQUE,titulo VARCHAR(200) NOT NULL,contenido TEXT NOT NULL,imagen VARCHAR(255),estado VARCHAR(20) NOT NULL DEFAULT 'activo' CHECK(estado IN ('activo','inactivo')),fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS auditoria_reservas (id BIGSERIAL PRIMARY KEY,reserva_id BIGINT NOT NULL REFERENCES reservas(id) ON DELETE RESTRICT,usuario_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,accion VARCHAR(20) NOT NULL CHECK(accion IN ('creada','confirmada','cancelada','completada','rechazada','actualizada')),estado_anterior VARCHAR(20),estado_nuevo VARCHAR(20),observaciones TEXT,fecha_accion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_reservas_usuario ON reservas(usuario_id);CREATE INDEX IF NOT EXISTS idx_reservas_estado ON reservas(estado);CREATE INDEX IF NOT EXISTS idx_disp_fecha ON disponibilidad_semanal(semana_inicio,semana_fin);CREATE INDEX IF NOT EXISTS idx_notif_usuario ON notificaciones(usuario_id,leida);
